name: Tox tests

on: [push, pull_request]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
  pidiff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e pidiff
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e cov
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install RPM
        run: sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e bandit
